#!/usr/bin/python -c "pass"
# ^ Trick for syntax highlighting in gedit...

Import('env')

ConfigFile = env.Object('ConfigFile.cpp')
event = env.Object("event.cpp")
Map = env.Object("map.cpp")
entity = env.Object("entity.cpp")
astar = env.Object("astar.cpp")
SConscript("entity/SConscript")
Import('Ents')

env.Program('../IrrRR', ['main.cpp'] + event + ConfigFile + Map + entity)
